backend:
  name: github
  repo: kevin-crawford/cpp-blog
media_folder: static/img
public_folder: /img
collections:
  - name: post
    label: Post
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: author, label: Author }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: podcast
    label: Podcast
    description: Audio Podcasts
    folder: "src/pages/podcasts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: author, label: Author }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
