backend:
  name: github
  repo: kevin-crawford/cpp-blog
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - name: post
    label: Post
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "path", label: "Path", widget: "hidden" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "Article Image",
          label: "Article Image",
          widget: "image",
          required: false,
        }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "type", label: "Type", widget: "hidden", default: "blog" }
  - name: podcast
    label: Podcast
    description: Audio Podcasts
    folder: "src/pages/podcasts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "Article Image",
          label: "Article Image",
          widget: "image",
          required: false,
        }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "type", label: "Type", widget: "hidden", default: "podcast" }
