backend:
  name: github
  repo: kevin-crawford/cpp-blog
media_folder: static/img
media_folder_relative: true
public_folder: img
site_url: https://cp-podcast.netlify.com/
display_url: https://cp-podcast.netlify.com/
collections:
  - name: post
    label: Post
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "path", label: "Path", widget: "hidden" }
      - { name: "author", label: "Author" , widget: "string"}
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "image",
          label: "Article Image",
          widget: "image",
          default: "src/images/waterpolo.jpg",
          required: false,
        }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "list", allow_add: true }
      - { name: "type", label: "Type", widget: "hidden", default: "blog" }
  - name: podcast
    label: Podcast
    description: Audio Podcasts
    folder: "src/pages/podcasts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "image",
          label: "Podcast Image",
          widget: "image",
          default: "src/images/podcast-default.png",
          required: false,
        }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { label: "Podcast File", name: "podcast_file", widget: "file" }
      - { name: "tags", label: "Tags", widget: "list", allow_add: true }
      - { name: "type", label: "Type", widget: "hidden", default: "podcast" }
